In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [4]:
#Data processing
# categorical data to numeric
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelencoder_X_1 =LabelEncoder()
X[:,1]=labelencoder_X_1.fit_transform(X[:,1])
   

In [5]:
X

array([[619, 0, 'Female', ..., 1, 1, 101348.88],
       [608, 2, 'Female', ..., 0, 1, 112542.58],
       [502, 0, 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 0, 'Female', ..., 0, 1, 42085.58],
       [772, 1, 'Male', ..., 1, 0, 92888.52],
       [792, 0, 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [6]:
labelencoder_X_2 =LabelEncoder()
X[:,2]=labelencoder_X_2.fit_transform(X[:,2])

In [7]:
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [8]:
onehotEncoder =OneHotEncoder(categorical_features=[1])
X= onehotEncoder.fit_transform(X).toarray()   

C:\Users\KINJAL\.conda\envs\py3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\KINJAL\.conda\envs\py3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [11]:
X=X[:,1:] #dummy variable trap

In [13]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [14]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

**lets make the ANN**

In [22]:
#import libraries
from keras.layers import Dense
from keras.models import Sequential

**initalizing the ANN**

In [30]:
classifier=Sequential()
#adding the input layer and the first hidden layer
classifier.add(Dense(units=6, kernel_initializer='uniform', input_dim=11, activation='relu'))

In [31]:
#adding the second hidden layer
classifier.add(Dense(units=6, kernel_initializer='uniform', activation='relu'))

In [32]:
classifier.add(Dense(units=1, kernel_initializer='uniform', activation='sigmoid'))

**Compiling the ANN**
 

In [34]:
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

W0918 23:52:07.152544 14796 deprecation_wrapper.py:119] From C:\Users\KINJAL\.conda\envs\py3\lib\site-packages\keras\optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0918 23:52:07.193431 14796 deprecation_wrapper.py:119] From C:\Users\KINJAL\.conda\envs\py3\lib\site-packages\keras\backend\tensorflow_backend.py:3376: The name tf.log is deprecated. Please use tf.math.log instead.

W0918 23:52:07.201411 14796 deprecation.py:323] From C:\Users\KINJAL\.conda\envs\py3\lib\site-packages\tensorflow\python\ops\nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [35]:
#fitting the ANN to the training set
classifier.fit(X_train, y_train, batch_size=10, epochs=100)


W0918 23:55:53.449402 14796 deprecation_wrapper.py:119] From C:\Users\KINJAL\.conda\envs\py3\lib\site-packages\keras\backend\tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.



Epoch 1/100
7500/7500 [==============================] - 2s 302us/step - loss: 0.4893 - acc: 0.7961
Epoch 2/100
7500/7500 [==============================] - 1s 107us/step - loss: 0.4284 - acc: 0.7963
Epoch 3/100
7500/7500 [==============================] - 1s 137us/step - loss: 0.4215 - acc: 0.8101
Epoch 4/100
7500/7500 [==============================] - 1s 118us/step - loss: 0.4156 - acc: 0.8280
Epoch 5/100
7500/7500 [==============================] - 1s 143us/step - loss: 0.4118 - acc: 0.8308
Epoch 6/100
7500/7500 [==============================] - 1s 136us/step - loss: 0.4087 - acc: 0.8324
Epoch 7/100
7500/7500 [==============================] - 1s 104us/step - loss: 0.4060 - acc: 0.8347
Epoch 8/100
7500/7500 [==============================] - 1s 104us/step - loss: 0.4049 - acc: 0.8341
Epoch 9/100
7500/7500 [==============================] - 1s 105us/step - loss: 0.4030 - acc: 0.8361
Epoch 10/100
7500/7500 [==============================] - 1s 137us/step - loss: 0.4019 - acc: 0.8339

7500/7500 [==============================] - 1s 109us/step - loss: 0.3768 - acc: 0.8401
Epoch 83/100
7500/7500 [==============================] - 1s 104us/step - loss: 0.3749 - acc: 0.8391
Epoch 84/100
7500/7500 [==============================] - 1s 103us/step - loss: 0.3731 - acc: 0.8433
Epoch 85/100
7500/7500 [==============================] - 1s 104us/step - loss: 0.3713 - acc: 0.8408
Epoch 86/100
7500/7500 [==============================] - 1s 108us/step - loss: 0.3714 - acc: 0.8415
Epoch 87/100
7500/7500 [==============================] - 1s 107us/step - loss: 0.3711 - acc: 0.8420
Epoch 88/100
7500/7500 [==============================] - 1s 111us/step - loss: 0.3690 - acc: 0.8431
Epoch 89/100
7500/7500 [==============================] - 1s 106us/step - loss: 0.3675 - acc: 0.8417
Epoch 90/100
7500/7500 [==============================] - 1s 104us/step - loss: 0.3673 - acc: 0.8441
Epoch 91/100
7500/7500 [==============================] - 1s 108us/step - loss: 0.3667 - acc: 0.8424
Epo

In [36]:
# make the prediction
y_pred=classifier.predict(X_test)

In [38]:
y_pred=(y_pred>0.5)

In [39]:
#making the confusion matrix
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)

In [43]:
cm

array([[1906,   85],
       [ 293,  216]], dtype=int64)

In [44]:
(1906+216)/2500 #accuaracy

0.8488